---
name: deploy

on:
  push:
    branches:
      - '*'

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4
      - name: Run Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v2
      - name: Build and test
        run: |
          nix develop --command make build test
